services:
  - type: web
    name: electronics-dashboard
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: sqlite
      mountPath: /opt/render/project/src/data
      sizeGB: 1
